import type FileReader from '../FileReader';
import type Vector3 from '../Vector3';

class ReadHeader {
    public readonly id: number;
    public readonly version: number;
    public readonly checksum: number;
    public readonly name: string;
    public readonly length: number;
    public readonly eyeposition: Vector3;
    public readonly illumposition: Vector3;
    public readonly hull_min: Vector3;
    public readonly hull_max: Vector3;
    public readonly view_bbmin: Vector3;
    public readonly view_bbmax: Vector3;
    public readonly flags: number;
    public readonly numbones: number;
    public readonly boneindex: number;
    public readonly numbonecontrollers: number;
    public readonly bonecontrollerindex: number;
    public readonly numhitboxsets: number;
    public readonly hitboxsetindex: number;
    public readonly numlocalanim: number;
    public readonly localanimindex: number;
    public readonly numlocalseq: number;
    public readonly localseqindex: number;
    public readonly activitylistversion: number;
    public readonly eventsindexed: number;
    public readonly numtextures: number;
    public readonly textureindex: number;
    public readonly numcdtextures: number;
    public readonly cdtextureindex: number;
    public readonly numskinref: number;
    public readonly numskinfamilies: number;
    public readonly skinindex: number;
    public readonly numbodyparts: number;
    public readonly bodypartindex: number;
    public readonly numlocalattachments: number;
    public readonly localattachmentindex: number;
    public readonly numlocalnodes: number;
    public readonly localnodeindex: number;
    public readonly localnodenameindex: number;
    public readonly numflexdesc: number;
    public readonly flexdescindex: number;
    public readonly numflexcontrollers: number;
    public readonly flexcontrollerindex: number;
    public readonly numflexrules: number;
    public readonly flexruleindex: number;
    public readonly numikchains: number;
    public readonly ikchainindex: number;
    public readonly nummouths: number;
    public readonly mouthindex: number;
    public readonly numlocalposeparameters: number;
    public readonly localposeparamindex: number;
    public readonly surfacepropindex: number;
    public readonly keyvalueindex: number;
    public readonly keyvaluesize: number;
    public readonly numlocalikautoplaylocks: number;
    public readonly localikautoplaylockindex: number;
    public readonly mass: number;
    public readonly contents: number;
    public readonly numincludemodels: number;
    public readonly includemodelindex: number;
    public readonly virtualModel: number;
    public readonly szanimblocknameindex: string;
    public readonly numanimblocks: number;
    public readonly animblockindex: number;
    public readonly animblockModel: number;
    public readonly bonetablebynameindex: number;
    public readonly pVertexBase: number;
    public readonly pIndexBase: number;
    public readonly constdirectionallightdot: number;
    public readonly rootLOD: number;
    public readonly numAllowedRootLODs: number;
    public readonly numflexcontrollerui: number;
    public readonly flexcontrolleruiindex: number;
    public readonly flVertAnimFixedPointScale: number;
    public readonly studiohdr2index: number;

    public constructor(file: FileReader) {
        this.id = file.readInt();
        this.version = file.readInt();
        this.checksum = file.readInt();
        this.name = file.readString(64);
        this.length = file.readInt();
        this.eyeposition = file.readVector3();
        this.illumposition = file.readVector3();
        this.hull_min = file.readVector3();
        this.hull_max = file.readVector3();
        this.view_bbmin = file.readVector3();
        this.view_bbmax = file.readVector3();
        this.flags = file.readInt();
        this.numbones = file.readInt();
        this.boneindex = file.readInt();
        this.numbonecontrollers = file.readInt();
        this.bonecontrollerindex = file.readInt();
        this.numhitboxsets = file.readInt();
        this.hitboxsetindex = file.readInt();
        this.numlocalanim = file.readInt();
        this.localanimindex = file.readInt();
        this.numlocalseq = file.readInt();
        this.localseqindex = file.readInt();
        this.activitylistversion = file.readInt();
        this.eventsindexed = file.readInt();
        this.numtextures = file.readInt();
        this.textureindex = file.readInt();
        this.numcdtextures = file.readInt();
        this.cdtextureindex = file.readInt();
        this.numskinref = file.readInt();
        this.numskinfamilies = file.readInt();
        this.skinindex = file.readInt();
        this.numbodyparts = file.readInt();
        this.bodypartindex = file.readInt();
        this.numlocalattachments = file.readInt();
        this.localattachmentindex = file.readInt();
        this.numlocalnodes = file.readInt();
        this.localnodeindex = file.readInt();
        this.localnodenameindex = file.readInt();
        this.numflexdesc = file.readInt();
        this.flexdescindex = file.readInt();
        this.numflexcontrollers = file.readInt();
        this.flexcontrollerindex = file.readInt();
        this.numflexrules = file.readInt();
        this.flexruleindex = file.readInt();
        this.numikchains = file.readInt();
        this.ikchainindex = file.readInt();
        this.nummouths = file.readInt();
        this.mouthindex = file.readInt();
        this.numlocalposeparameters = file.readInt();
        this.localposeparamindex = file.readInt();
        this.surfacepropindex = file.readInt();
        this.keyvalueindex = file.readInt();
        this.keyvaluesize = file.readInt();
        this.numlocalikautoplaylocks = file.readInt();
        this.localikautoplaylockindex = file.readInt();
        this.mass = file.readFloat();
        this.contents = file.readInt();
        this.numincludemodels = file.readInt();
        this.includemodelindex = file.readInt();
        this.virtualModel = file.readInt();
        this.szanimblocknameindex = file.readStringZeroTerminated();
        this.numanimblocks = file.readInt();
        this.animblockindex = file.readInt();
        this.animblockModel = file.readInt();
        this.bonetablebynameindex = file.readInt();
        this.pVertexBase = file.readInt();
        this.pIndexBase = file.readInt();
        this.constdirectionallightdot = file.readByte();
        this.rootLOD = file.readByte();
        this.numAllowedRootLODs = file.readByte();
        file.readByteArray(1); // unused
        file.readInt(); // unused4
        this.numflexcontrollerui = file.readInt();
        this.flexcontrolleruiindex = file.readInt();
        this.flVertAnimFixedPointScale = file.readFloat();
        file.readIntArray(1); // unused3
        this.studiohdr2index = file.readInt();
        file.readIntArray(1); // unused2
    }
}

export default ReadHeader;
