import type Vector3 from '../../mathematics/Vector3.ts';
import type FileReader from '../../utilities/FileReader.ts';

class SequenceDescription {
    public readonly baseptr: number;
    public readonly szlabelindex: string;
    public readonly szactivitynameindex: string;
    public readonly flags: number;
    public readonly activity: number;
    public readonly actweight: number;
    public readonly numevents: number;
    public readonly eventindex: number;
    public readonly bbmin: Vector3;
    public readonly bbmax: Vector3;
    public readonly numblends: number;
    public readonly animindexindex: number;
    public readonly movementindex: number;
    public readonly groupsize: number[];
    public readonly paramindex: number[];
    public readonly paramstart: number[];
    public readonly paramend: number[];
    public readonly paramparent: number;
    public readonly fadeintime: number;
    public readonly fadeouttime: number;
    public readonly localentrynode: number;
    public readonly localexitnode: number;
    public readonly nodeflags: number;
    public readonly entryphase: number;
    public readonly exitphase: number;
    public readonly lastframe: number;
    public readonly nextseq: number;
    public readonly pose: number;
    public readonly numikrules: number;
    public readonly numautolayers: number;
    public readonly autolayerindex: number;
    public readonly weightlistindex: number;
    public readonly posekeyindex: number;
    public readonly numiklocks: number;
    public readonly iklockindex: number;
    public readonly keyvalueindex: number;
    public readonly keyvaluesize: number;
    public readonly cycleposeindex: number;
    public readonly activitymodifierindex: number;
    public readonly numactivitymodifiers: number;
    public readonly unused: number[];

    public constructor(file: FileReader, public readonly fileStart: number) {
        this.baseptr = file.readInt();
        this.szlabelindex = file.readZeroTerminatedString(fileStart);
        this.szactivitynameindex = file.readZeroTerminatedString(fileStart);
        this.flags = file.readInt();
        this.activity = file.readInt();
        this.actweight = file.readInt();
        this.numevents = file.readInt();
        this.eventindex = file.readInt();
        this.bbmin = file.readVector3();
        this.bbmax = file.readVector3();
        this.numblends = file.readInt();
        this.animindexindex = file.readInt();
        this.movementindex = file.readInt();
        this.groupsize = file.readIntArray(2);
        this.paramindex = file.readIntArray(2);
        this.paramstart = file.readFloatArray(2);
        this.paramend = file.readFloatArray(2);
        this.paramparent = file.readInt();
        this.fadeintime = file.readFloat();
        this.fadeouttime = file.readFloat();
        this.localentrynode = file.readInt();
        this.localexitnode = file.readInt();
        this.nodeflags = file.readInt();
        this.entryphase = file.readFloat();
        this.exitphase = file.readFloat();
        this.lastframe = file.readFloat();
        this.nextseq = file.readInt();
        this.pose = file.readInt();
        this.numikrules = file.readInt();
        this.numautolayers = file.readInt();
        this.autolayerindex = file.readInt();
        this.weightlistindex = file.readInt();
        this.posekeyindex = file.readInt();
        this.numiklocks = file.readInt();
        this.iklockindex = file.readInt();
        this.keyvalueindex = file.readInt();
        this.keyvaluesize = file.readInt();
        this.cycleposeindex = file.readInt();
        this.activitymodifierindex = file.readInt();
        this.numactivitymodifiers = file.readInt();
        this.unused = file.readIntArray(5);
    }
}

export default SequenceDescription;
